export const ROUTES = {
  LOGIN:      '/login',
  DASHBOARD:  '/',
  USERS:      '/users',
  USER_DETAIL:'/users/:userId',
  SESSIONS:   '/sessions',
  EVENTS:     '/events',
  SCREENS:    '/screens',
  SCREEN_USAGE:  '/screen-usage',
  MODULE_USAGE:  '/module-usage',
  WORKFLOW_BREAK:'/workflow-break',
  ROLE_USAGE:    '/role-usage',
  ROLE_ANALYTICS:      '/role-analytics',
  DEALER_ANALYTICS:    '/dealer-analytics',
  FEATURE_USAGE:       '/feature-usage',
  REALTIME:   '/realtime',
  RETENTION:  '/retention',
  REPORTS:    '/reports',
};
